### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by LeoGo2017** [xiaozhouwang/kaggle-porto-seguro#1]
run nn_model290.py，get the error:

Traceback (most recent call last):
  File "/Users/leoliu/PycharmProjects/kaggle/Porto Seguro’s Safe Driver Prediction/2nd-solution/code/nn_model290.py", line 234, in <module>model.fit(xtr_cat_list, ytr, epochs=20, batch_size=512, verbose=2, validation_data=[xte_cat_list, yte])
  File "/Users/leoliu/anaconda2/lib/python2.7/site-packages/keras/engine/training.py", line 1650, in fit validation_steps=validation_steps)
  File "/Users/leoliu/anaconda2/lib/python2.7/site-packages/keras/engine/training.py", line 1213, in _fit_loop outs = f(ins_batch)
  File "/Users/leoliu/anaconda2/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 2352, in __call__ **self.session_kwargs)
  File "/Users/leoliu/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 889, in run run_metadata_ptr)
  File "/Users/leoliu/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1120, in _run feed_dict_tensor, options, run_metadata)
  File "/Users/leoliu/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run options, run_metadata)
  File "/Users/leoliu/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1336, in _do_call  raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: <exception str() failed>

**Comment by Fansgithub2019** [comment]
I have the same problem. Have you solved it?
